### ISSUE TITLE
Feature to set Nullable mode

### ISSUE THREAD

**Issue by schultzcole** [Cysharp/CsprojModifier#2]
I think it would be useful to be able to set the default Nullable mode for csproj files.

As it is currently, you can set a compiler argument to build with nullable enabled like so: <https://stackoverflow.com/questions/64229527/customizing-csproj-in-unity-enable-nullable-reference-types>
However this only applies when Unity builds your code, it unfortunately isn't picked up by the IDE. Setting the nullable mode in the csproj would allow the IDE to provide nullability hints.

**Comment by mayuki** [comment]
It would be nice to have support for Nullable Reference Types.
The workaround is to create a .props and import it so that the IDE can recognize it, but I would like to consider to implement Nullable mode feature.
